name: Continuous Integration Testing

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: '0 0 * * *'


jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:13
        env:
          DB_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_PORT: 5432
          POSTGRES_DB: test
          DB_SCHEMA: nest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Copy .env and Install Dependencies"
        run: cp .env.ci .env && npm install 
      - name: "Build"
        run: npm run build
      - name: "Set Up Database"
        run: npm run migrate:up
      - name: "Run Tests"
        run: npm run test:cov